### ISSUE TITLE
not available in webpack3

### ISSUE THREAD

**Issue by wjeek** [wuct/elastic-apm-sourcemap-webpack-plugin#13]
this plugin is not available in webpack3 
there is an error when using it

**Comment by wuct** [comment]
Yes, as it is mentioned in [`peerDependencies`](https://github.com/wuct/elastic-apm-sourcemap-webpack-plugin/blob/master/package.json#L143). It is easy to make current implementation compatible with webpack 3, but we need to find a way to make integration tests for both webpack 3 and 4.

**Comment by wuct** [comment]
@wjeek I've created #15 which is backward compatible with Webpack 3. You can use that branch if you want.
